### PR TITLE
Fix idempotency when modifying PAM rules

### PR DESCRIPTION
**Pull request by Thulium-Drake**
Hi there,

Thanks for this role! I noticed that the tasks for PAM aren't completely idempotent, as they both want to be at the same location.

Cheers!

### CODE REVIEW

**Comment by jeremydescamps** [comment]
HI @Thulium-Drake  ,

thanks for your feedback !

I did few tests that were not mentioning any idempotence problem on these tasks.
Can you please provide an example of usage you use and more information about the problem you get ?

Regards.

**Comment by Thulium-Drake** [comment]
Hi there, 

Well, when running the role multiple times, it repeats the lines for ```auth``` and ```account``` as the module was configured to put both lines immediately before the line with ```pam_keyinit.so```. And because of that, it kept reporting as changed.

On the customer system where I used this role (which I don't have access to right now) I saw something along the lines of:

```
auth pam_userdb.so db=/etc/vsftpd/login
account pam_userdb.so db=/etc/vsftpd/login
auth pam_userdb.so db=/etc/vsftpd/login
account pam_userdb.so db=/etc/vsftpd/login
auth pam_userdb.so db=/etc/vsftpd/login
account pam_userdb.so db=/etc/vsftpd/login
auth pam_userdb.so db=/etc/vsftpd/login
account pam_userdb.so db=/etc/vsftpd/login
auth pam_userdb.so db=/etc/vsftpd/login
account pam_userdb.so db=/etc/vsftpd/login
auth pam_userdb.so db=/etc/vsftpd/login
account pam_userdb.so db=/etc/vsftpd/login
```

after a couple of days :-)

And with this change, it will do it just once and then be happy.

**Comment by Thulium-Drake** [comment]
ping @jeremydescamps  :)

**Comment by jeremydescamps** [comment]
Hi @Thulium-Drake ,

based on the `main` branch, I am able to run the module with the following config : 

```yaml
- hosts: ubuntu01
  gather_facts: yes
  become: yes
  roles:
    - role: ansible-role-vsftpd
      vsftpd_enable_virt_users: true
      vsftpd_virt_users:
        - username: xat
          password: xat
          guest_username: www-data
          local_root: /var/www/
          write_enable: yes
        - username: xat2
          password: xat2
          guest_username: www-data
          local_root: /var/www/
          write_enable: yes
```

This above config does not have any idempotence issue, except for the task `generating default virtual users database`, because this file is re-generated any time the playbook is executed.

So far, I am not able to reproduce what you are talking about.

Can you please provide the full playbook config you are using with the `main` version of the role ?
Plus, can you tell me which file is being updated every time you run the playbook ?

Thanks a lot.
Regards.

**Comment by Thulium-Drake** [comment]
Hi there, sorry for the late reply! 

Please find the requested information below:

Ansible results (recorded with ARA):
image

PAM.d file: 
image

Inventory file with variables:
```
# VSFTPd settings
vsftpd_enable_virt_users: true
vsftpd_chroot_local_users: true
vsftpd_virt_users:
  - username: 'netadmin'
    guest_username: 'netadmin'
    password: shh_its_secret!
    local_root: '/home/netadmin'
    write_enable: true
```

And in the main playbook I 'just' call the role, just like you did.

Ansible version: 2.13.3
Target OS: RHEL8

**Comment by Xat59** [comment]
hi @Thulium-Drake , thanks a lot for all these details.

I am now able to reproduce what you are talking about, only on RHEL/CentOS based OSes. When using Debian/Ubuntu, this behavior does not appear.

I'll let you informed. Thanks !

**Comment by Xat59** [comment]
I am able to reproduce your issue on RHEL based OSes only, but your PR does not fix it.

I've just created a RHEL8 from scratch, then used your playbook as an example, and applied with ansible.
Your PR does not affect the `/etc/pam.d/vsftpd` file, whereas applying the playbook with virtual users must modify the `/etc/pam.d/vsftpd` file.

Feel free to test your PR using a newly created RHEL8 instance, you'll see it does not work.

**Comment by Thulium-Drake** [comment]
Sorry for the late reply! My attention was required elsewhere, I'll look into this and update the PR :-)

**Comment by Thulium-Drake** [comment]
I also reworked the 'generate virtual user database' task, which now gives me the following output when running it with this branch:

Can you check it on your end as well? :-)

```
PLAY [Run a specific role against machines] *************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [semaphore.lab]

TASK [Run role] *****************************************************************************************************
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed
 in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [vsftpd : installing vsftpd package] ***************************************************************************
ok: [semaphore.lab] => (item=vsftpd)
ok: [semaphore.lab] => (item=libdb-utils)

TASK [vsftpd : copying vsftpd systemd service file for vsftpd] ******************************************************
skipping: [semaphore.lab]

TASK [vsftpd : configuring systemd for vsftpd] **********************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : configuring systemd for vsftpd] **********************************************************************
ok: [semaphore.lab]

TASK [vsftpd : configuring vsftpd instance] *************************************************************************
ok: [semaphore.lab]

TASK [vsftpd : creating vsftpd configuration directory] *************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : configuring vsftpd instance] *************************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : installing vsftpd package] ***************************************************************************
skipping: [semaphore.lab] => (item=vsftpd) 

TASK [vsftpd : copying vsftpd systemd service file for vsftpd instance] *********************************************
skipping: [semaphore.lab]

TASK [vsftpd : configuring systemd for vsftpd instance] *************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : configuring systemd for vsftpd] **********************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : configuring vsftpd instance] *************************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : configuring vsftpd instance] *************************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : creating default users config directory] *************************************************************
ok: [semaphore.lab]

TASK [vsftpd : creating vsftpd users config directory] **************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : creating default users config] ***********************************************************************
ok: [semaphore.lab] => (item={'username': 'netadmin', 'guest_username': 'netadmin', 'password': 'bananas', 'local_root': '/home/netadmin', 'write_enable': True})

TASK [vsftpd : creating vsftpd users config] ************************************************************************
skipping: [semaphore.lab] => (item={'username': 'netadmin', 'guest_username': 'netadmin', 'password': 'bananas', 'local_root': '/home/netadmin', 'write_enable': True}) 

TASK [vsftpd : configuring pam for default vsftpd virtual users 1/2] ************************************************
ok: [semaphore.lab]

TASK [vsftpd : configuring pam for default vsftpd virtual users 2/2] ************************************************
ok: [semaphore.lab]

TASK [vsftpd : configuring pam for vsftpd vsftpd virtual users] *****************************************************
skipping: [semaphore.lab]

TASK [vsftpd : adding virtual users to default database] ************************************************************
ok: [semaphore.lab]

TASK [vsftpd : adding virtual users to vsftpd] **********************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : generating default virtual users database] ***********************************************************
skipping: [semaphore.lab]

TASK [vsftpd : creating empty vsftpd login file] ********************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : generating vsftpd virtual users database] ************************************************************
skipping: [semaphore.lab]

TASK [vsftpd : changing mode for default virtual users database] ****************************************************
ok: [semaphore.lab]

TASK [vsftpd : changing mode for vsftpd virtual users database] *****************************************************
skipping: [semaphore.lab]

PLAY RECAP **********************************************************************************************************
semaphore.lab              : ok=10   changed=0    unreachable=0    failed=0    skipped=18   rescued=0    ignored=0 
```

EDIT: my config:

```
# VSFTPd settings
vsftpd_enable_virt_users: true
vsftpd_chroot_local_users: true
vsftpd_virt_users:
  - username: 'netadmin'
    guest_username: 'netadmin'
    password: 'bananas'
    local_root: '/home/netadmin'
    write_enable: true
```

The playbook is a playbook that will load just a single role, nothing special :)

**Comment by jeremydescamps** [comment]
Hi @Thulium-Drake , I did some test with your PR and it appears your PR does not deal with `/etc/pam.d/vsftpd` file while it should.

I am trying to add lines in the `/etc/pam.d/vsftpd` file through the `pamd` ansible module, by avoiding having any duplicate lines.

**Comment by jeremydescamps** [comment]
@Thulium-Drake 
Can you confirm it has been fixed by this PR https://github.com/Xat59/ansible-role-vsftpd/pull/13 ?

**Pull request closed without merging**
